version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: sportera-mongo-dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Kungfu22
      MONGO_INITDB_DATABASE: sportera
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - sportera-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sportera-backend-dev
    env_file: ./backend/.env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: yarn dev
    depends_on:
      - mongodb
    networks:
      - sportera-dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sportera-frontend-dev
    env_file: ./frontend/.env.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
    depends_on:
      - backend
    networks:
      - sportera-dev

volumes:
  mongo_data_dev:

networks:
  sportera-dev:
    driver: bridge